INSERT INTO `data_item` (`id`, `nom`, `num_img`, `num_ligne`, `type_item`, `color`, `contient_item`) VALUES
(96, 'Branche séchée', '01', 1, 'cueillette', 'blanc', 'non'),
(97, 'Racine fossile', '02', 2, 'cueillette', 'vert', 'non'),
(98, 'Lys médicianal', '03', 3, 'cueillette', 'vert', 'non'),
(99, 'Coquille d\'argent', '04', 4, 'cueillette', 'vert', 'non'),
(100, 'Branche de fer', '05', 5, 'cueillette', 'blanc', 'non'),
(101, 'Racine lunaire', '06', 6, 'cueillette', 'vert', 'non'),
(102, 'Mousse osseuse', '07', 7, 'cueillette', 'vert', 'non'),
(103, 'Branche d\'argent', '08', 8, 'cueillette', 'blanc', 'non'),
(104, 'Corail primitif', '09', 9, 'cueillette', 'vert', 'non'),
(105, 'Pétale d\'or', '10', 10, 'cueillette', 'vert', 'non'),
(106, 'Racine draconique', '11', 11, 'cueillette', 'vert', 'non'),
(107, 'Branche d\'ambre', '12', 12, 'cueillette', 'blanc', 'non'),
(108, 'Lichen absorbant', '13', 13, 'cueillette', 'vert', 'non'),
(109, 'Champignon métamorphe', '14', 14, 'cueillette', 'vert', 'non'),
(110, 'Racine millénaire', '15', 15, 'cueillette', 'vert', 'non'),
(111, 'Branche ancestrale', '16', 16, 'cueillette', 'blanc', 'non'),
(112, 'Chardon carnivore', '17', 17, 'cueillette', 'vert', 'non'),
(113, 'Bois de l\immortalité', '18', 18, 'cueillette', 'orange', 'non'),
(114, 'Poivron draconique', '19', 19, 'cueillette', 'vert', 'non'),
(115, 'Feuille nervurée du dragon bleu', '20', 20, 'cueillette', 'orange', 'non'),
(116, 'Orchidée fragile', '21', 21, 'cueillette', 'vert', 'non'),
(117, 'Herbe d\'argent du vent cinglant', '22', 22, 'cueillette', 'orange', 'non'),
(118, 'Perle céleste', '23', 23, 'cueillette', 'vert', 'non'),
(119, 'Anneaux de ramages de mille ans', '24', 24, 'cueillette', 'orange', 'non'),
(120, 'Brindille cristalisée', '25', 25, 'cueillette', 'blanc', 'non'),
(121, 'Graine de départ', '26', 26, 'cueillette', 'vert', 'non'),
(122, 'Fruit de la noix magique', '27', 27, 'cueillette', 'vert', 'non'),
(123, 'Pétale de fleur de cristal glacé', '28', 28, 'cueillette', 'vert', 'non'),
(124, 'Lichen aux reflets bleus', '29', 29, 'cueillette', 'vert', 'non'),
(125, 'Sirop d\'erable pur', '30', 30, 'cueillette', 'vert', 'non'),
(126, 'Foin de pepperland', '31', 31, 'cueillette', 'orange', 'non'),
(127, 'Plante marbrée inconnue', '32', 32, 'cueillette', 'violet', 'oui'),
(128, 'Herbes d\'echo fantaisies', '33', 33, 'cueillette', 'violet', 'non'),
(129, 'Ecorce grummeleuse', '34', 34, 'cueillette', 'blanc', 'non'),
(130, 'Super champi magique', '35', 35, 'cueillette', 'vert', 'non'),
(131, 'Fougère de velours', '36', 36, 'cueillette', 'vert', 'non'),
(132, 'Olive magique farcie', '37', 37, 'cueillette', 'orange', 'non'),
(133, 'plante sombre inconnue', '38', 38, 'cueillette', 'violet', 'oui'),
(134, 'Racine de fleur du diable d\'ombre sanguinaire', '39', 39, 'cueillette', 'violet', 'non'),
(135, 'Collier de graines', '40', 40, 'cueillette', 'vert', 'non'),
(136, 'Racines permafrost', '41', 41, 'cueillette', 'vert', 'non'),
(137, 'Lauriers d\'or', '42', 42, 'cueillette', 'orange', 'non'),
(138, 'Camélia de libellule', '43', 43, 'cueillette', 'vert', 'non'),
(139, 'Plante chaotique', '44', 44, 'cueillette', 'violet', 'oui'),
(140, 'Vigne ancestrale', '45', 45, 'cueillette', 'violet', 'non'),
(141, 'Ecorce ciselée', '46', 46, 'cueillette', 'blanc', 'non'),
(142, 'Perle de rosée', '47', 47, 'cueillette', 'vert', 'non'),
(143, 'Rose de l\'aurore', '48', 48, 'cueillette', 'orange', 'non'),
(144, 'Lotus à épines', '49', 49, 'cueillette', 'vert', 'non'),
(145, 'Plante troublante inconnue', '50', 50, 'cueillette', 'violet', 'oui'),
(146, 'Algue parasite', '51', 51, 'cueillette', 'violet', 'non'),
(147, 'Racines de l\'arbre ancien', '52', 52, 'cueillette', 'blanc', 'non'),
(148, 'Toxine de plante', '53', 53, 'cueillette', 'vert', 'non'),
(149, 'Baiser du coquelicot', '54', 54, 'cueillette', 'orange', 'non'),
(150, 'Herbe marine', '55', 55, 'cueillette', 'vert', 'non'),
(151, 'Plante tordue inconnue', '56', 56, 'cueillette', 'violet', 'oui'),
(152, 'Nid fleuri de lutin', '57', 57, 'cueillette', 'violet', 'non'),
(153, 'Racine de l\'arbre araignée', '58', 58, 'cueillette', 'blanc', 'non'),
(154, 'Cheveux de sprite des rêves', '59', 59, 'cueillette', 'vert', 'non'),
(155, 'Narcisse de jade noir', '60', 60, 'cueillette', 'orange', 'non'),
(156, 'Feuille de cauchemar', '61', 61, 'cueillette', 'vert', 'non'),
(157, 'Plante déformée inconnue', '62', 62, 'cueillette', 'violet', 'oui'),
(158, 'Narcisse de jade rouge', '63', 63, 'cueillette', 'violet', 'non'),
(159, 'Herbe de verre', '64', 64, 'cueillette', 'blanc', 'non'),
(160, 'Fruit du temps', '65', 65, 'cueillette', 'vert', 'non'),
(161, 'Rose sanglante démoniaque', '66', 66, 'cueillette', 'orange', 'non'),
(162, 'Fleur du diable infernal', '67', 67, 'cueillette', 'vert', 'non'),
(163, 'Plante capiteuse inconnue', '68', 68, 'cueillette', 'violet', 'oui'),
(164, 'Algue ondulée illusoire', '69', 69, 'cueillette', 'violet', 'non'),
(165, 'Fleur dimensionnelle', '70', 70, 'cueillette', 'rouge', 'non')

