INSERT INTO `data_item` (`id`, `nom`, `num_img`, `num_ligne`, `type_item`, `color`, `contient_item`) VALUES
(1, 'Minerai de bronze', '01', 1, 'minerai', 'blanc', 'non'),
(2, 'Gemme brute', '02', 2, 'minerai', 'vert', 'non'),
(3, 'Gemme lunaire', '03', 3, 'minerai', 'vert', 'non'),
(4, 'Gemme ambre', '04', 4, 'minerai', 'vert', 'non'),
(5, 'Minerai de fer', '05', 5, 'minerai', 'blanc', 'non'),
(6, 'Gemme énergétique', '06', 6, 'minerai', 'vert', 'non'),
(7, 'Gemme irradiante', '07', 7, 'minerai', 'vert', 'non'),
(8, 'Minerai d\'acier', '08', 8, 'minerai', 'blanc', 'non'),
(9, 'Gemme bariolée', '09', 9, 'minerai', 'vert', 'non'),
(10, 'Or ancien', '10', 10, 'minerai', 'vert', 'non'),
(11, 'Or mat', '11', 11, 'minerai', 'vert', 'non'),
(12, 'Minerai noir', '12', 12, 'minerai', 'blanc', 'non'),
(13, 'Gemme sanguine', '13', 13, 'minerai', 'vert', 'non'),
(14, 'Gemme vitale', '14', 14, 'minerai', 'vert', 'non'),
(15, 'Gemme lumineuse', '15', 15, 'minerai', 'vert', 'non'),
(16, 'Minerai de platine', '16', 16, 'minerai', 'blanc', 'non'),
(17, 'Gemme émeraude', '17', 17, 'minerai', 'vert', 'non'),
(18, 'Minerai de l\'écaille de dragon', '18', 18, 'minerai', 'orange', 'non'),
(19, 'Argent lunaire', '19', 19, 'minerai', 'vert', 'non'),
(20, 'Métal sacré', '20', 20, 'minerai', 'orange', 'non'),
(21, 'Gemme astrale', '21', 21, 'minerai', 'vert', 'non'),
(22, 'Cristal des mers', '22', 22, 'minerai', 'orange', 'non'),
(23, 'Gemme obscure', '23', 23, 'minerai', 'vert', 'non'),
(24, 'Noyau terrestre bouillant', '24', 24, 'minerai', 'orange', 'non'),
(25, 'Minéral de cristal du fantôme', '25', 25, 'minerai', 'blanc', 'non'),
(26, 'Argent brillant', '26', 26, 'minerai', 'vert', 'non'),
(27, 'Acier sanglant', '27', 27, 'minerai', 'vert', 'non'),
(28, 'Cristal du fossile de la bête des glaces', '28', 28, 'minerai', 'vert', 'non'),
(29, 'Veine de glace cristallisée', '29', 29, 'minerai', 'vert', 'non'),
(30, 'Ambre dorée', '30', 30, 'minerai', 'vert', 'non'),
(31, 'Billes mystiques', '31', 31, 'minerai', 'orange', 'non'),
(32, 'Roche Marbrée', '32', 32, 'minerai', 'violet', 'oui'),
(33, 'Pierre magnétique flottante', '33', 33, 'minerai', 'violet', 'non'),
(34, 'Graine de schtroumpf', '34', 34, 'minerai', 'blanc', 'non'),
(35, 'Lingot de malepierre', '35', 35, 'minerai', 'vert', 'non'),
(36, 'Sable de tatooine', '36', 36, 'minerai', 'vert', 'non'),
(37, 'Perles de poppins', '37', 37, 'minerai', 'orange', 'non'),
(38, 'Roche sombre inconnue', '38', 38, 'minerai', 'violet', 'oui'),
(39, 'Emeuraude ombreuse ardente', '39', 39, 'minerai', 'violet', 'non'),
(40, 'Crottin de rastar', '40', 40, 'minerai', 'vert', 'non'),
(41, 'Agate gelée', '41', 41, 'minerai', 'vert', 'non'),
(42, 'Cristal arc-en-ciel', '42', 42, 'minerai', 'orange', 'non'),
(43, 'Augite rose', '43', 43, 'minerai', 'vert', 'non'),
(44, 'Roche chaotique', '44', 44, 'minerai', 'violet', 'oui'),
(45, 'Cristal d\'âme de bête', '45', 45, 'minerai', 'violet', 'non'),
(46, 'Gemme étrange', '46', 46, 'minerai', 'blanc', 'non'),
(47, 'Pierre de l\'âme', '47', 47, 'minerai', 'vert', 'non'),
(48, 'Larme de sang', '48', 48, 'minerai', 'orange', 'non'),
(49, 'Emeuraude arc-en-ciel', '49', 49, 'minerai', 'vert', 'non'),
(50, 'Roche troublante', '50', 50, 'minerai', 'violet', 'oui'),
(51, 'Ambre alternative', '51', 51, 'minerai', 'violet', 'non'),
(52, 'Gemme étincelante', '52', 52, 'minerai', 'blanc', 'non'),
(53, 'Glace améthyste', '53', 53, 'minerai', 'vert', 'non'),
(54, 'Essence de larme de démon', '54', 54, 'minerai', 'orange', 'non'),
(55, 'Cristal à mousse verte', '55', 55, 'minerai', 'vert', 'non'),
(56, 'Roche tordue inconnue', '56', 56, 'minerai', 'violet', 'oui'),
(57, 'Electrum liquide', '57', 57, 'minerai', 'violet', 'non'),
(58, 'Cristal de mort furieux', '58', 58, 'minerai', 'blanc', 'non'),
(59, 'Pierre d\'ombrelune', '59', 59, 'minerai', 'vert', 'non'),
(60, 'Pierre de l\'ancien volcan', '60', 60, 'minerai', 'orange', 'non'),
(61, 'Orbe du soleil', '61', 61, 'minerai', 'vert', 'non'),
(62, 'Roche déformé inconnue', '62', 62, 'minerai', 'violet', 'oui'),
(63, 'Gemme de cristal fondu', '63', 63, 'minerai', 'violet', 'non'),
(64, 'Minerai de larme de rêve', '64', 64, 'minerai', 'blanc', 'non'),
(65, 'Sable de cristal givré', '65', 65, 'minerai', 'vert', 'non'),
(66, 'Cristal polaire', '66', 66, 'minerai', 'orange', 'non'),
(67, 'Diamant de sang', '67', 67, 'minerai', 'vert', 'non'),
(68, 'Roche capiteuse inconnue', '68', 68, 'minerai', 'violet', 'oui'),
(69, 'Morceau de météorite milénaire', '69', 69, 'minerai', 'violet', 'non'),
(70, 'Gemme de feu impure', '70', 70, 'minerai', 'rouge', 'non'),
(71, 'Coffre à trésor ancestral', '71', 71, 'minerai', 'blanc', 'oui'),
(72, 'Boîte cassée et trempée', '72', 72, 'minerai', 'blanc', 'oui'),
(73, 'Coffre à trésor royal ancien', '73', 73, 'minerai', 'blanc', 'oui'),
(74, 'Vieille boîte de stockage', '74', 74, 'minerai', 'blanc', 'oui'),
(75, 'Boîte à bijoux scellée', '75', 75, 'minerai', 'blanc', 'oui'),
(76, 'Héritage perdu', '76', 76, 'minerai', 'blanc', 'oui'),
(77, 'Ration ouvre-boîte', '77', 77, 'minerai', 'blanc', 'oui'),
(78, 'Coffre osseux', '78', 78, 'minerai', 'blanc', 'oui'),
(79, 'Mystérieuses boîte à magie', '79', 79, 'minerai', 'blanc', 'oui'),
(80, 'Coffre couvert de mousse', '80', 80, 'minerai', 'blanc', 'oui'),
(81, 'Boîte à trésor remplie de sorts', '81', 81, 'minerai', 'blanc', 'oui'),
(82, 'Coffre à trésor des dieux', '82', 82, 'minerai', 'blanc', 'oui'),
(83, 'Boîte secrète couverte de givre', '83', 83, 'minerai', 'blanc', 'oui'),
(84, 'Boîte en pierre', '84', 84, 'minerai', 'blanc', 'oui'),
(85, 'Coffre à trésor du village de l\'île du sud', '85', 85, 'minerai', 'blanc', 'oui'),
(86, 'Cercueil de pierre du volcan', '86', 86, 'minerai', 'blanc', 'oui'),
(87, 'Coffre à trésor de cristal gelé', '87', 87, 'minerai', 'blanc', 'oui'),
(88, 'Coffre scellé du glacier', '88', 88, 'minerai', 'blanc', 'oui'),
(89, 'Vase de porcelaine glacé', '89', 89, 'minerai', 'blanc', 'oui'),
(90, 'Coffret couvert de neige', '90', 90, 'minerai', 'blanc', 'oui'),
(91, 'Ecrin d\'horloger', '91', 91, 'minerai', 'blanc', 'oui'),
(92, 'Malle de voyageur', '92', 92, 'minerai', 'blanc', 'oui'),
(93, 'Coffre aux ressorts de gel', '93', 93, 'minerai', 'blanc', 'oui'),
(94, 'Coffre au trésor des abîmes', '94', 94, 'minerai', 'blanc', 'oui'),
(95, 'Coffre de verre près de permafrost', '95', 95, 'minerai', 'blanc', 'oui')